name: Build and publish artifact
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate .env template
        run: |
          echo SOURCE_LANGUAGE= >> .env
          echo TARGET_LANGUAGE= >> .env
          echo DEEP_L_API_KEY= >> .env
          echo API_URL= >> .env
          echo FILE_NAME= >> .env

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --name docx-translator main.py

      - name: Upload build artifacts (snapshot)
        uses: actions/upload-artifact@v4
        with:
          name: docx-translator-snapshot
          path: |
            dist/docx-translator.exe
            .env
